<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4def2a4acbb5675312a504418e5d2ec1
{
    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpMussel\\Core\\' => 15,
        ),
        'M' => 
        array (
            'Maikuolan\\Common\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpMussel\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmussel/core/src',
        ),
        'Maikuolan\\Common\\' => 
        array (
            0 => __DIR__ . '/..' . '/maikuolan/common/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4def2a4acbb5675312a504418e5d2ec1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4def2a4acbb5675312a504418e5d2ec1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4def2a4acbb5675312a504418e5d2ec1::$classMap;

        }, null, ClassLoader::class);
    }
}
