<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'phpMussel\\Core\\' => array($vendorDir . '/phpmussel/core/src'),
    'Maikuolan\\Common\\' => array($vendorDir . '/maikuolan/common/src'),
);
